apiVersion: v1
kind: Namespace
metadata:
  name: dbaas-dynamic-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbaas-dynamic-plugin
  namespace: dbaas-dynamic-plugin
  labels:
    app: dbaas-dynamic-plugin
    app.kubernetes.io/component: dbaas-dynamic-plugin
    app.kubernetes.io/instance: dbaas-dynamic-plugin
    app.kubernetes.io/part-of: dbaas-dynamic-plugin
    app.openshift.io/runtime-namespace: dbaas-dynamic-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbaas-dynamic-plugin
  template:
    metadata:
      labels:
        app: dbaas-dynamic-plugin
    spec:
      containers:
        - name: dbaas-dynamic-plugin
          image: quay.io/ecosystem-appeng/dbaas-dynamic-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
          env:
            - name: DBAAS_OPERATOR_VERSION
              value: 'dbaas-operator.v0.1.1'
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: dbaas-dynamic-plugin
  namespace: dbaas-dynamic-plugin
  labels:
    app: dbaas-dynamic-plugin
    app.kubernetes.io/component: dbaas-dynamic-plugin
    app.kubernetes.io/instance: dbaas-dynamic-plugin
    app.kubernetes.io/part-of: dbaas-dynamic-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: dbaas-dynamic-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: dbaas-dynamic-plugin
spec:
  displayName: 'OpenShift DataBase as a Service Dynamic Plugin'
  service:
    name: dbaas-dynamic-plugin
    namespace: dbaas-dynamic-plugin
    port: 9001
    basePath: '/'
