apiVersion: v1
kind: Namespace
metadata:
  name: console-dynamic-foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-dynamic-foo
  namespace: console-dynamic-foo
  labels:
    app: console-dynamic-foo
    app.kubernetes.io/component: console-dynamic-foo
    app.kubernetes.io/instance: console-dynamic-foo
    app.kubernetes.io/part-of: console-dynamic-foo
    app.openshift.io/runtime-namespace: console-dynamic-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-dynamic-foo
  template:
    metadata:
      labels:
        app: console-dynamic-foo
    spec:
      containers:
        - name: console-dynamic-foo
          image: quay.io/rawagner/console-dynamic-foo
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - '--ssl'
            - '--cert=/var/serving-cert/tls.crt'
            - '--key=/var/serving-cert/tls.key'
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: console-dynamic-foo
  namespace: console-dynamic-foo
  labels:
    app: console-dynamic-foo
    app.kubernetes.io/component: console-dynamic-foo
    app.kubernetes.io/instance: console-dynamic-foo
    app.kubernetes.io/part-of: console-dynamic-foo
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: console-dynamic-foo
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: console-dynamic-foo
spec:
  displayName: 'OpenShift Console Demo Plugin'
  service:
    name: console-dynamic-foo
    namespace: console-dynamic-foo
    port: 9001
    basePath: '/'
